// User queries
export {
  GET_CURRENT_USER,
  GET_USER_BY_ID,
  GET_USERS,
  GET_USER_STATISTICS,
  GET_USER_ACTIVITIES,
  GET_USER_SESSIONS,
  GET_USER_BALANCE_HISTORY,
  GET_USER_DOCUMENTS,
  GET_USER_REFERRALS,
  SEARCH_USERS,
  GET_USER_PROFILE_SUMMARY,
  GET_ONLINE_USERS,
  GET_VIP_USERS
} from './user';

// Payment queries
export {
  GET_PAYMENTS,
  GET_PAYMENT_BY_ID,
  GET_DEPOSITS,
  GET_WITHDRAWALS,
  GET_PAYMENT_METHODS,
  GET_PAYMENT_STATISTICS,
  GET_TRANSACTIONS,
  GET_USER_TRANSACTIONS,
  GET_BONUSES,
  GET_USER_BONUSES,
  GET_COMMISSIONS,
  GET_PENDING_PAYMENTS,
  GET_PAYMENT_DASHBOARD,
  GET_PAYMENT_METHOD_STATS,
  GET_USER_PAYMENT_SUMMARY
} from './payment';

// Game queries
export {
  GET_GAMES,
  GET_GAME_BY_ID,
  GET_GAME_STATISTICS,
  GET_BETS,
  GET_BET_BY_ID,
  GET_BET_STATISTICS,
  GET_USER_BETS,
  GET_GAME_BETS,
  GET_BETTING_LIMITS,
  GET_GAME_SESSIONS,
  GET_JACKPOTS,
  GET_TOURNAMENTS,
  GET_TOURNAMENT_BY_ID,
  GET_GAME_PROVIDERS,
  GET_GAME_CATEGORIES,
  GET_POPULAR_GAMES,
  GET_PENDING_BETS,
  GET_GAME_DASHBOARD,
  SEARCH_GAMES
} from './game'; 