// User fragments
export {
  USER_BASIC_FRAGMENT,
  USER_DETAIL_FRAGMENT,
  USER_STATS_FRAGMENT,
  USER_ACTIVITY_FRAGMENT,
  USER_SESSION_FRAGMENT,
  USER_BALANCE_FRAGMENT,
  USER_LIMITS_FRAGMENT,
  USER_DOCUMENT_FRAGMENT,
  USER_REFERRAL_FRAGMENT
} from './user';

// Payment fragments
export {
  PAYMENT_BASIC_FRAGMENT,
  PAYMENT_DETAIL_FRAGMENT,
  PAYMENT_METHOD_FRAGMENT,
  TRANSACTION_FRAGMENT,
  PAYMENT_STATS_FRAGMENT,
  DEPOSIT_FRAGMENT,
  WITHDRAWAL_FRAGMENT,
  PAYMENT_PROCESSOR_FRAGMENT,
  BONUS_FRAGMENT,
  COMMISSION_FRAGMENT
} from './payment';

// Game fragments
export {
  GAME_BASIC_FRAGMENT,
  GAME_DETAIL_FRAGMENT,
  GAME_STATS_FRAGMENT,
  BET_FRAGMENT,
  BET_STATS_FRAGMENT,
  BETTING_LIMIT_FRAGMENT,
  GAME_SESSION_FRAGMENT,
  JACKPOT_FRAGMENT,
  TOURNAMENT_FRAGMENT,
  GAME_PROVIDER_FRAGMENT,
  GAME_CATEGORY_FRAGMENT
} from './game'; 